### PR TITLE
auto update on money change without pressing the button

### PR DESCRIPTION
**Pull request by mahanmoulaei**

### CODE REVIEW

**Comment by mascotte-scripts** [comment]
Whats the point when you can just create an event to refresh the HUD and then trigger the event from ESX's add/remove money function?

**Comment by mahanmoulaei** [comment]
> Whats the point when you can just create an event to refresh the HUD and then trigger the event from ESX's add/remove money function?

What I did was executing the command from ESX's add/remove money...
I don't think there would be a big difference in triggering an event from ESX's add/remove money or executing a command from that event.

The only difference I can see is that every time the player presses the Config.DefaultKey(which is "B" in our case), it triggers a server callback which is absolutely unnecessary and can affect the performance. 
So I think it's better if I change the ExecuteCommand to TriggerEvent so the server callback only would be triggered if there is a change in the money amount(not every time the player presses the  Config.DefaultKey!).

**Comment by mascotte-scripts** [comment]
I should have been clearer, I meant whats the point of keeping it as a command when it can be executed through an event. It's unnecessary to use a command in this case

**Comment by mascotte-scripts** [comment]
Changing the command to a function and triggering an event within addmoney/removemoney to execute the function is far more efficient. The function you wrote works fine, but for best results the trigger should be placed within the addmoney/removemoney functions in es_extended so it will refresh it every time an ingame transcation credits or debits one of the money accounts - and that way, regardless of what script changes the accounts balance it'll update as it should, because the triggers nested within the frameworks function for adding/removing cash

**Comment by mascotte-scripts** [comment]
So for example here's how I'm doing it within my framework, it's my equivalent of removemoney:

> function RemoveAccountMoney(source, identifier, account, amount)
>     local wallet = GetBalance(source, identifier, 'wallet')
>     local bank = GetBalance(source, identifier, 'bank')
>     if account == 'wallet' then 
>             local sum = wallet - amount
>             local newbalance = SetResourceKvpInt(('users:%s:CharacterData:wallet'):format(identifier), sum) TriggerClientEvent('Player:UpdateHudWalletBalance', source) -- After the money is removed, this event triggers the HUD to refresh
>     elseif account == 'bank' then
>             local sum = bank - amount
>             local newbalance = SetResourceKvpInt(('users:%s:CharacterData:bank'):format(identifier), sum)
>         TriggerClientEvent('Player:UpdateHudBankBalance', source)
>     else
>         print('Unknown Error: Function RemoveAccountMoney()')
>     end
> end

**Comment by mahanmoulaei** [comment]
I understand what you mean now...
What I understand from you is it's better if we trigger the update HUD function directly from the framework, but not everyone likes to modify their base codes really!
I'm ok with that...I've overhauled my es_extended so far but I know lots of people who don't even touch their framework because they are afraid of breaking codes.

This client-side event "esx:setAccountMoney" is triggered by es_extended by default when there is a change in players' money, and I'm calling the function to check the new money and update it when "esx:setAccountMoney" event is called.

You are right about the command that should be changed to either a function or an event and that's exactly what I did =]

**Review by 2Girls1CJ — APPROVED** [review]
nice sorry for the late reply just got back into this.

**Pull request merged**
